# Extra autostart processes
# exec-once = uwsm-app -- swayosd-server (disabled: managed by systemd service)
# exec-once = uwsm-app -- my-service
exec-once = rclone mount gdrive: /home/ahmet/GoogleDrive --vfs-cache-mode full --vfs-cache-max-age 24h --vfs-cache-max-size 10G --vfs-read-chunk-size 32M --dir-cache-time 72h --vfs-fast-fingerprint --no-modtime

